export const StudentConstant = {
  GET: "GET",
  ADD: "ADD",
  UPDATE: "UPDATE",
  GETFAMILYMEMBERS: "GETFAMILYMEMBERS",
  ADDFAMILYMEMBER: "ADDFAMILYMEMBER",
  UPDATEFAMILYMEMBER: "UPDATEFAMILYMEMBER",
  DELETEFAMILYMEMBER: "DELETEFAMILYMEMBER",
  UPDATEFAMILYMEMBERNATIONALITY: "UPDATEFAMILYMEMBERNATIONALITY",
};
